<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      // 1
      // Promise.resolve()
      //   .then(() => {
      //     console.log(1)
      //   })
      //   .catch(() => {
      //     console.log(2) // 状态为失败的时候才会执行，所以这里不会执行，只会输出1,3
      //   })
      //   .then(() => {
      //     console.log(3)
      //   })

      // 2
      // Promise.resolve()
      //   .then(() => {
      //     console.log(1)
      //     throw '出问题了'
      //   })
      //   .catch(() => {
      //     console.log(2)
      //     // 默认是返回之歌成功的 promise,所以不会执行下面的 catch，只输出 1 2
      //   })
      //   .catch(() => {
      //     console.log(3)
      //   })

      // 3
      // Promise.resolve()
      //   .then(() => {
      //     console.log(1)
      //     throw new Error('出问题了') // 会走到 catch 方法
      //   })
      //   .catch(() => {
      //     console.log(2)
      //   })
      //   .then(() => {
      //     console.log(3)
      //     // 都会输出 1 2 3 因为 catch 默认返回的是一个成功的 promise 对象
      //   })

      // 4
      // async function fn() {
      //   return 100
      // }
      // ;(async function () {
      //   const a = fn()
      //   const b = await fn()
      //   console.log(a) // promsie 对象
      //   console.log(b) // 100
      // })()

      // 5
      // ;(async function () {
      //   console.log('开始')
      //   const a = await 100
      //   console.log(a) // 100
      //   const b = await Promise.resolve(200)
      //   console.log(b) //200
      //   const c = await Promise.reject(300) // await 后面接收一个成功的 promise 对象，失败状态的 promise 对象的话要用 try catch 捕获，不然会报错，后面的代码不会执行
      //   console.log(c) // 不会执行
      //   console.log('结束') // 不会执行
      // })()

      // 6
      async function async1() {
        console.log(1) // 2
        await async2()

        // await 下面作为回调内容都是微任务
        console.log(2) // 6
        setTimeout(() => {
          // 宏任务
          console.log(9) // 9
        })
      }

      async function async2() {
        console.log(3) // 3
      }

      console.log(4) // 1

      setTimeout(() => {
        // 宏任务
        console.log(5) // 8
      })

      async1()

      new Promise((resolve, reject) => {
        resolve()
        console.log(6) // 4
      }).then(() => {
        // 微任务
        console.log(7) // 7
      })

      console.log(8) // 5

      // 4 1 3 6 8 2 7 5 9
    </script>
  </body>
</html>
